### PR TITLE
Let dumb-init reap zombie processes

### LINKED ISSUE #34: Zombie processes
Running the container for a while will produce thousands of zombie process until all check start failing
```
icinga   2411824 3668603  0 04:34 ?        00:00:00 [ping] <defunct>
icinga   2411826 3668603  0 04:34 ?        00:00:00 [ping] <defunct>
icinga   2412155 3668603  0 04:35 ?        00:00:00 [ping] <defunct>
icinga   2412162 3668603  0 04:35 ?        00:00:00 [ping] <defunct>
icinga   2412164 3668603  0 04:35 ?        00:00:00 [ping] <defunct>
icinga   2412560 3668603  0 04:36 ?        00:00:00 [ping] <defunct>
icinga   2412572 3668603  0 04:36 ?        00:00:00 [ping] <defunct>
icinga   2412574 3668603  0 04:36 ?        00:00:00 [ping] <defunct>
icinga   2412948 3668603  0 04:37 ?        00:00:00 [ping] <defunct>
icinga   2412952 3668603  0 04:37 ?        00:00:00 [ping] <defunct>
icinga   2412954 3668603  0 04:37 ?        00:00:00 [ping] <defunct>
icinga   2413246 3668603  0 04:38 ?        00:00:00 [ping] <defunct>
icinga   2413285 3668603  0 04:38 ?        00:00:00 [ping] <defunct>
icinga   2413287 3668603  0 04:38 ?        00:00:00 [ping] <defunct>
icinga   2413646 3668603  0 04:39 ?        00:00:00 [ping] <defunct>
icinga   2413691 3668603  0 04:39 ?        00:00:00 [ping] <defunct>
icinga   2413693 3668603  0 04:39 ?        00:00:00 [ping] <defunct>
icinga   2414028 3668603  0 04:40 ?        00:00:00 [ping] <defunct>
icinga   2414037 3668603  0 04:40 ?        00:00:00 [ping] <defunct>
icinga   2414039 3668603  0 04:40 ?        00:00:00 [ping] <defunct>
icinga   2414369 3668603  0 04:41 ?        00:00:00 [ping] <defunct>
icinga   2414375 3668603  0 04:41 ?        00:00:00 [ping] <defunct>
icinga   2414377 3668603  0 04:41 ?        00:00:00 [ping] <defunct>
icinga   2414775 3668603  0 04:42 ?        00:00:00 [ping] <defunct>
icinga   2414786 3668603  0 04:42 ?        00:00:00 [ping] <defunct>
icinga   2414788 3668603  0 04:42 ?        00:00:00 [ping] <defunct>
icinga   2415147 3668603  0 04:43 ?        00:00:00 [ping] <defunct>
icinga   2415155 3668603  0 04:43 ?        00:00:00 [ping] <defunct>
icinga   2415157 3668603  0 04:43 ?        00:00:00 [ping] <defunct>
icinga   2415449 3668603  0 04:44 ?        00:00:00 [ping] <defunct>
icinga   2415492 3668603  0 04:44 ?        00:00:00 [ping] <defunct>
icinga   2415494 3668603  0 04:44 ?        00:00:00 [ping] <defunct>
icinga   2415910 3668603  0 04:45 ?        00:00:00 [ping] <defunct>
icinga   2415968 3668603  0 04:45 ?        00:00:00 [ping] <defunct>
icinga   2415970 3668603  0 04:45 ?        00:00:00 [ping] <defunct>
icinga   2416339 3668603  0 04:46 ?        00:00:00 [ping] <defunct>
icinga   2416353 3668603  0 04:46 ?        00:00:00 [ping] <defunct>
icinga   2416355 3668603  0 04:46 ?        00:00:00 [ping] <defunct>
icinga   2416707 3668603  0 04:47 ?        00:00:00 [ping] <defunct>
icinga   2416715 3668603  0 04:47 ?        00:00:00 [ping] <defunct>
icinga   2416719 3668603  0 04:47 ?        00:00:00 [ping] <defunct>
icinga   2417270 3668603  0 04:48 ?        00:00:00 [ping] <defunct>
icinga   2417284 3668603  0 04:48 ?        00:00:00 [ping] <defunct>
icinga   2417286 3668603  0 04:48 ?        00:00:00 [ping] <defunct>
icinga   2418026 3668603  0 04:49 ?        00:00:00 [ping] <defunct>
icinga   2418897 3668603  0 04:50 ?        00:00:00 [ping] <defunct>
icinga   2418939 3668603  0 04:50 ?        00:00:00 [ping] <defunct>
icinga   2420034 3668603  0 04:51 ?        00:00:00 [ping] <defunct>
icinga   2420044 3668603  0 04:51 ?        00:00:00 [ping] <defunct>
icinga   2422232 3668603  0 04:54 ?        00:00:00 [ping] <defunct>
icinga   2423345 3668603  0 04:57 ?        00:00:00 [ping] <defunct>
```

### PR DESCRIPTION
**Pull request by Al2Klimov**
fixes #34

### CODE REVIEW

**Comment by Al2Klimov** [comment]
## Before

```
➜  docker-icinga2 git:(master) cat dumbinit/etc/icinga2/conf.d/my.conf
object CheckCommand "zombie" {
	command = [ "bash", "-c", "sleep 5 </dev/null >/dev/null 2>&1 &" ]
}

object Host "zombie" {
	check_command = "zombie"
	check_interval = 1s
}
➜  docker-icinga2 git:(master) docker run --name dumbinit --rm -dv $(pwd)/dumbinit:/data icinga/icinga2

e8ea8f13f6d95a3f3e6c08bfc25176da0d1132e37c10b099a471d2f74dc2b019
➜  docker-icinga2 git:(master) docker exec -it dumbinit ps -efH
UID        PID  PPID  C STIME TTY          TIME CMD
icinga     127     0  0 12:45 pts/0    00:00:00 ps -efH
icinga       1     0  3 12:45 ?        00:00:00 /usr/lib/x86_64-linux-gnu/icinga
icinga      43     1  1 12:45 ?        00:00:00   /usr/lib/x86_64-linux-gnu/icin
icinga      52    43  0 12:45 ?        00:00:00     /usr/lib/x86_64-linux-gnu/ic
icinga      78     1  0 12:45 ?        00:00:00   [sleep] <defunct>
icinga      80     1  0 12:45 ?        00:00:00   [sleep] <defunct>
icinga      82     1  0 12:45 ?        00:00:00   [sleep] <defunct>
icinga      84     1  0 12:45 ?        00:00:00   [sleep] <defunct>
icinga      86     1  0 12:45 ?        00:00:00   [sleep] <defunct>
icinga      88     1  0 12:45 ?        00:00:00   [sleep] <defunct>
icinga      90     1  0 12:45 ?        00:00:00   [sleep] <defunct>
icinga      92     1  0 12:45 ?        00:00:00   [sleep] <defunct>
icinga      94     1  0 12:45 ?        00:00:00   [sleep] <defunct>
icinga      96     1  0 12:45 ?        00:00:00   [sleep] <defunct>
icinga      98     1  0 12:45 ?        00:00:00   [sleep] <defunct>
icinga     101     1  0 12:45 ?        00:00:00   [sleep] <defunct>
icinga     103     1  0 12:45 ?        00:00:00   [sleep] <defunct>
icinga     111     1  0 12:45 ?        00:00:00   [sleep] <defunct>
icinga     113     1  0 12:45 ?        00:00:00   [sleep] <defunct>
icinga     115     1  0 12:45 ?        00:00:00   sleep 5
icinga     119     1  0 12:45 ?        00:00:00   sleep 5
icinga     121     1  0 12:45 ?        00:00:00   sleep 5
icinga     123     1  0 12:45 ?        00:00:00   sleep 5
icinga     125     1  0 12:45 ?        00:00:00   sleep 5
➜  docker-icinga2 git:(master)
```

## After

```
➜  docker-icinga2 git:(bugfix/zombie-processes-34) docker run --name dumbinit --rm -dv $(pwd)/dumbinit:/data icinga/icinga2
d829c81d11e01570d64047dad97b2403176978f93bc6a9f589c989b35df45074
➜  docker-icinga2 git:(bugfix/zombie-processes-34) docker exec -it dumbinit ps -efH
UID        PID  PPID  C STIME TTY          TIME CMD
icinga     196     0  0 12:50 pts/0    00:00:00 ps -efH
icinga       1     0  0 12:49 ?        00:00:00 dumb-init -c icinga2 daemon
icinga      13     1  2 12:49 ?        00:00:00   /usr/lib/x86_64-linux-gnu/icin
icinga      45    13  1 12:49 ?        00:00:00     /usr/lib/x86_64-linux-gnu/ic
icinga      54    45  0 12:49 ?        00:00:00       /usr/lib/x86_64-linux-gnu/
icinga     192    54  0 12:50 ?        00:00:00         /usr/lib/nagios/plugins/
icinga     193   192  0 12:50 ?        00:00:00           /bin/ping -4 -n -U -w
icinga     182     1  0 12:50 ?        00:00:00   sleep 5
icinga     185     1  0 12:50 ?        00:00:00   sleep 5
icinga     189     1  0 12:50 ?        00:00:00   sleep 5
icinga     191     1  0 12:50 ?        00:00:00   sleep 5
icinga     195     1  0 12:50 ?        00:00:00   sleep 5
➜  docker-icinga2 git:(bugfix/zombie-processes-34) docker exec -it dumbinit ps -efH
UID        PID  PPID  C STIME TTY          TIME CMD
icinga     283     0  0 12:50 pts/0    00:00:00 ps -efH
icinga       1     0  0 12:49 ?        00:00:00 dumb-init -c icinga2 daemon
icinga      13     1  1 12:49 ?        00:00:00   /usr/lib/x86_64-linux-gnu/icin
icinga      45    13  0 12:49 ?        00:00:00     /usr/lib/x86_64-linux-gnu/ic
icinga      54    45  0 12:49 ?        00:00:00       /usr/lib/x86_64-linux-gnu/
icinga     266     1  0 12:50 ?        00:00:00   sleep 5
icinga     274     1  0 12:50 ?        00:00:00   sleep 5
icinga     277     1  0 12:50 ?        00:00:00   sleep 5
icinga     279     1  0 12:50 ?        00:00:00   sleep 5
icinga     282     1  0 12:50 ?        00:00:00   sleep 5
➜  docker-icinga2 git:(bugfix/zombie-processes-34)
```

**Comment by Al2Klimov** [comment]
Would be nice to have this merged before the next release.

**Comment by julianbrost** [comment]
By next release you mean 2.12.2, 2.12.3 or 2.13.0?

**Comment by Al2Klimov** [comment]
All of them.

**Comment by julianbrost** [comment]
How will this interact in combination with https://github.com/Icinga/icinga2/pull/8512 (not) being merged? If that one is not merged, this should just do nothing as there are no zombie processes? So that PR is not required for this one, it would just remove stuff that's no longer needed if this one gets merged, right?

**Comment by Al2Klimov** [comment]
Exactly.

**Review by julianbrost — COMMENTED** [review]
Tested it and it worked, however I think that maybe we want to "hide" dumb-init within entrypoint for two reasons:
1. To allow running Icinga 2 with a custom command in the container without having to care about dumb-init. I have `command: icinga2 daemon -x notice` in the `docker-compose.yml` for my test cluster and first thought that this didn't work until I noticed that my command override actually disabled dumb-init.
2. Less clutter in the output of `docker ps`

**Comment by julianbrost** [comment]
Just noticed that the [dumb-init readme](https://github.com/Yelp/dumb-init/#usage) uses `--` to separate the command, so probably we should also do this.

**Comment by Al2Klimov** [comment]
But the man page doesn't.

File: entrypoint/main.go [hunk 1]
```diff
@@ -120,9 +121,13 @@ func entrypoint() error {
 				return errSt
 			}
 		}
+
+		if len(command) > 1 && command[0] == "icinga2" && command[1] == "daemon" {
```
Comment (julianbrost) [inline entrypoint/main.go]: Why this specific check? Isn't entrypoint run for PID 1 inside the container anyways, so if you run `docker exec`, we won't get here? Or am I missing some other case?

**Comment by julianbrost** [comment]
On using `--` or not: probably doesn't make a big difference as it stops interpreting arguments after the first one that doesn't start with `-`:

```
root@6feb8a61afaf:/# dumb-init -c icinga2 --version | head -1 
icinga2 - The Icinga 2 network monitoring daemon (version: r2.12.2-1)
root@6feb8a61afaf:/# dumb-init -c -- icinga2 --version | head -1
icinga2 - The Icinga 2 network monitoring daemon (version: r2.12.2-1)
```

So you would only notice a difference if someonet tries to run something like `--version` as a command (but there the exit code will differ):

```
root@6feb8a61afaf:/# dumb-init -c --version
dumb-init v1.2.2
root@6feb8a61afaf:/# dumb-init -c -- --version
[dumb-init] --version: No such file or directory
```

File: entrypoint/main.go (hunk 1 above)
Comment (Al2Klimov) [reply entrypoint/main.go]: Why PID==1 or why icinga2 daemon?

Comment (julianbrost) [reply entrypoint/main.go]: Actually both. Shouldn't Docker only call the entrypoint if it is PID 1? And would it hurt to start other commands with dumb-init?

Comment (Al2Klimov) [reply entrypoint/main.go]: 1. Just to be sure. Not PID 1 – no need for this.
2. Yes, e.g. bash due to dumb-init **-c**.

Comment (julianbrost) [reply entrypoint/main.go]: What's the problem with `dumb-init -c bash`?

Comment (Al2Klimov) [reply entrypoint/main.go]: It's unnecessary.

Comment (julianbrost) [reply entrypoint/main.go]: But if it works fine (which I think it does), this special handling here is unnecessary. ;)

Comment (Al2Klimov) [reply entrypoint/main.go]: I consider `dumb-init -c bash` more unnecessary.

Comment (julianbrost) [reply entrypoint/main.go]: I don't see why we would want special handling here. There are a few situations where this might give unexpected behavior:

1. Explicitly calling `/usr/sbin/icinga2` instead of just `icinga2`
2. Running the container with a command like `/data/init.sh` that will later `exec icinga2`
3. Possibly one could pass arguments between `icinga2` and `daemon`? At least it does not complain if you run something like `icinga -Dfoo=bar daemon`.

**Review by julianbrost — APPROVED** [review]
